language: python
python:
  - 3.6
before_install:
  - pip install flake8
  - flake8 pykmssig
install:
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py install
script:
- python -m unittest discover tests